apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tromsfylke-no

resources:
  - ../../../base

commonLabels:
  fintlabs.no/org-id: tromsfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-flyt-frontend_tromsfylke-no"
      - op: replace
        path: "/spec/image"
        value: ghcr.io/fintlabs/fint-flyt-frontend-tromsfylke-no-beta
      - op: replace
        path: "/spec/orgId"
        value: "tromsfylke.no"
      - op: replace
        path: "/spec/env/0/value"
        value: "/beta/tromsfylke-no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/beta/tromsfylke-no"
    target:
      kind: Application
      name: fint-flyt-frontend

  - patch: |-
      - op: replace
        path: "/spec/basePath"
        value: "/beta/tromsfylke-no"
    target:
      kind: FLAISSso
      name: fint-flyt-auth-forward-sso

