name: CD

on:
  repository_dispatch:
    types: [ trigger-cd ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          tags: type=sha,enable=true,priority=100,prefix=shaF-,suffix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-to-aks:
    name: deploy for ${{ matrix.org }} to ${{ matrix.cluster }}
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        org:
          - afk-no
          - agderfk-no
          - bfk-no
          - ffk-no
          - fintlabs-no
          - innlandetfylke-no
          - mrfylke-no
          - nfk-no
          - ofk-no
          - rogfk-no
          - telemarkfylke-no
          - tromsfylke-no
          - trondelagfylke-no
          - vestfoldfylke-no
          - vlfk-no

        cluster:
          - aks-beta-fint-2021-11-23
          - aks-api-fint-2022-02-08
        exclude:
          - org: fintlabs-no
            cluster: aks-api-fint-2022-02-08
          - org: agderfk-no
            cluster: aks-beta-fint-2021-11-23
          - org: ffk-no
            cluster: aks-beta-fint-2021-11-23
          - org: innlandetfylke-no
            cluster: aks-beta-fint-2021-11-23
          - org: mrfylke-no
            cluster: aks-beta-fint-2021-11-23
          - org: nfk-no
            cluster: aks-beta-fint-2021-11-23
          - org: rogfk-no
            cluster: aks-beta-fint-2021-11-23
          - org: telemarkfylke-no
            cluster: aks-beta-fint-2021-11-23
          - org: vestfoldfylke-no
            cluster: aks-beta-fint-2021-11-23

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get environment
        uses: actions/github-script@v7
        id: environment
        with:
          script: return '${{ matrix.cluster }}'.split('-')[1]
          result-encoding: string

      - name: Get resource group name
        uses: actions/github-script@v7
        id: resource-group
        with:
          script: return 'rg-aks-${{ steps.environment.outputs.result }}'
          result-encoding: string

      - name: Bake manifests with Kustomize
        id: bake
        uses: azure/k8s-bake@v2
        with:
          renderEngine: 'kustomize'
          kustomizationPath: 'kustomize/overlays/${{ matrix.org }}/${{ steps.environment.outputs.result }}'

      - uses: azure/login@v1
        with:
          creds: "${{ secrets[format('AKS_{0}_FINT_GITHUB', steps.environment.outputs.result)] }}"

      - uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.32'

      - name: Set the target cluster
        uses: azure/aks-set-context@v3
        with:
          cluster-name: '${{ matrix.cluster }}'
          resource-group: '${{ steps.resource-group.outputs.result }}'
          admin: 'true'
          use-kubelogin: 'true'

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: ${{ needs.build-and-push.outputs.tags }}
          namespace: ${{ matrix.org }}
